pipeline:

  validate:
    group: validate
    image: chrisns/packer-ansible
    environment:
    commands:
      - export HOME=/home/packer
      - packer validate packer.json

  inspect:
    group: validate
    image: chrisns/packer-ansible
    environment:
    commands:
      - export HOME=/home/packer
      - packer inspect packer.json

  build:
    image: chrisns/packer-ansible
    environment:
    commands:
      - export HOME=/home/packer
      - packer build packer.json

  packer-copy-prod:
    group: copy
    image: chrisns/packer-encrypt-copy
    commands:
      - export filters="--owner 093401982388 --filters "Name=name,Values=dq-data-pipeline-server*""
      - export aws_id=${PROD_ACC_ID}
      - export aws_key=${PROD_ACC_KEY}
      - export region=eu-west-2
      - export HOME=/home/packer
      - cd /home/packer
      - ./build.sh
    when:
      event: push
      branch: master

  packer-copy-notprod:
    group: copy
    image: chrisns/packer-encrypt-copy
    commands:
      - export filters="--owner 093401982388 --filters "Name=name,Values=dq-data-pipeline-server*""
      - export aws_id=${NOTPROD_ACC_ID}
      - export aws_key=${NOTPROD_ACC_KEY}
      - export region=eu-west-2
      - export HOME=/home/packer
      - cd /home/packer
      - ./build.sh
    when:
      event: push
      branch: master
